import { Item } from "./types";

export const SEEDS: Item[] = [
  { id: "1", title: "Апельсин", calories: "47" },
  { id: "2", title: "Арахис жареный", calories: "600" },
  { id: "3", title: "Банан", calories: "90" },
  { id: "4", title: "Виноград", calories: "78" },
  { id: "5", title: "Груша", calories: "57" },
  { id: "6", title: "Инжир сушеный", calories: "260" },
  { id: "7", title: "Йогурт греч Млековита", calories: "124" },
  { id: "8", title: "Йогурт Danio", calories: "109" },
  { id: "9", title: "Йогурт Fruvita", calories: "87" },
  { id: "10", title: "Капуста квашенная", calories: "19" },
  { id: "11", title: "Капуста свежая", calories: "28" },
  { id: "12", title: "Картофель вареный", calories: "76" },
  { id: "13", title: "Колбаса вареная", calories: "224" },
  { id: "14", title: "Конфеты", calories: "460" },
  { id: "15", title: "Куриная отбивная", calories: "168" },
  { id: "16", title: "Курица с грибами", calories: "90" },
  { id: "17", title: "Мандарин", calories: "47" },
  { id: "18", title: "Огурец", calories: "15" },
  { id: "19", title: "Огурец квашеный", calories: "11" },
  { id: "20", title: "Окорок жареный", calories: "195" },
  { id: "21", title: "Олия", calories: "899" },
  { id: "22", title: "Орех грецкий", calories: "680" },
  { id: "23", title: "Помидор", calories: "20" },
  { id: "24", title: "Сыр твердый", calories: "360" },
  { id: "25", title: "Хлеб", calories: "266" },
  { id: "26", title: "Яблоки сушеные", calories: "250" },
  { id: "27", title: "Яблоко", calories: "52" },
  { id: "28", title: "Яйцо вареное", calories: "160" },
  { id: "29", title: "Крекер", calories: "420" },
];
